### PR TITLE
feat: add swipe cell

### PR DESCRIPTION
**Pull request by szqingt**
## add swipe cell component

related #252 。
Vue and React components need to be completed, Maybe the someone can finish it, or when I'm free

### Credits
https://github.com/youzan/vant/tree/main/packages/vant/src/swipe-cell

### CODE REVIEW

**Comment by yx376642000** [comment]
需要补充一下demo

**Comment by szqingt** [comment]
> 需要补充一下demo

The mean of closing this pr means that it is not needed, or it needs to be supplemented and then re-submit pr？

**Comment by yx376642000** [comment]
I'm sorry that I closed your PR without communicating with you first. 
Thank you very much for your contribution, but the code lacks a key part. Without Demo, we cannot verify whether the code is usable.
At the same time, we also completed the development of the component ourselves and adopted some of your code.
Thank you again, and look forward to your more contributions

**Comment by yx376642000** [comment]
> I'm sorry that I closed your PR without communicating with you first.
> Thank you very much for your contribution, but the code lacks a key part. Without Demo, we cannot verify whether the code is usable.
> At the same time, we also completed the development of the component ourselves and adopted some of your code.
> Thank you again, and look forward to your more contributions

**Comment by yx376642000** [comment]
> > 需要补充一下demo
> 
> The mean of closing this pr means that it is not needed, or it needs to be supplemented and then re-submit pr？

I'm sorry that I closed your PR without communicating with you first.
Thank you very much for your contribution, but the code lacks a key part. Without Demo, we cannot verify whether the code is usable.
At the same time, we also completed the development of the component ourselves and adopted some of your code.
Thank you again, and look forward to your more contributions

**Pull request closed without merging**
