### PR TITLE
fix(react): prevent double invoking

### LINKED ISSUE #56: [按钮]  设置事件会重复执行
### Quark Design 版本

1.0.12

### 重现链接

_No response_

### 重现步骤

import React, { useState } from 'react';
import { Button } from '@quarkd/quark-react';
// import { Button } from 'antd';

const Index = () => {
  const [count, setCount] = useState(0);
  console.log(count);
  return (
    <div>
      <Button
        onClick={(e) => {
          setCount((count) => count + 1);
        }}
      >
        我是一个按钮 {count}
      </Button>
    </div>
  );
};

export default Index;

### 期望结果

1

### 实际结果

2

### 框架版本

react

### 浏览器版本

_No response_

### 系统版本

_No response_

### Node版本

_No response_

### 补充说明

_No response_

### PR DESCRIPTION
**Pull request by vaakian**
closes #56

### CODE REVIEW

**Comment by Maidang1** [comment]
@vaakian I think it can be call many times, maybe we can use `Set.has()` to judge if it is a native method. like this:

```javascript
const nativeEvents = /* #__PURE__ */ Object.keys(HTMLElement.prototype)
  .filter(eventName => eventName.startsWith('on'))
  .map(eventName => eventName.slice(2));

const nativeEventsSet = new Set(nativeEvents)

export function isNativeEvent(eventName: string) {
  return nativeEventsSet.has(eventName)
};
```

**Comment by vaakian** [comment]
Good idea, I've just added it.

**Comment by sanqi-med** [comment]
In quark， such as dialog、radio  has custom event 'close'、'change',
`const nativeEvents = /* #__PURE__ */ Object.keys(HTMLElement.prototype)
  .filter(eventName => eventName.startsWith('on'))
  .map(eventName => eventName.slice(2));`

nativeEvents alse has chaneg， this will filte quark custom event.

**Comment by vaakian** [comment]
> In quark， such as dialog、radio has custom event 'close'、'change', `const nativeEvents = /* #__PURE__ */ Object.keys(HTMLElement.prototype) .filter(eventName => eventName.startsWith('on')) .map(eventName => eventName.slice(2));`
> 
> nativeEvents alse has chaneg， this will filte quark custom event.

As I mentioned before, those events will be registered/updated by `React` itself when passing props to it. 


https://github.com/hellof2e/quark-design/blob/a4c4b7f0b538b2d723a98c0809b156cbff154899/packages/quark-reactify/src/index.ts#L63

**Comment by vaakian** [comment]
I've tested `<Field>` component.

This `onFocus` will also be triggered twice, because it matches native event.
```js
<Field onFocus={(e) => console.log(e)}></Field>
```

But `onChange` don't trigger at all, so this is a bug from `Field` component itself. (should also be triggered twice as `onFocus`)
```js
<Field onChange={(e) => console.log(e)}></Field>
```

**Comment by sanqi-med** [comment]
> The core logic:
> All native events will be register by React.
> Custom events should be register by quark manually using `this.setEvent(...)`.

@vaakian you are right。quark now has filter click、 focus、 blur ,other native event I think can not need be use in use quark.which scen can need use another native event ?

**Comment by sanqi-med** [comment]
I will close this pr. if need， you can reopen it, thank you!

**Pull request closed without merging**
